version: '3'
services:
  play_rosbag:
    build:
      context: .
    environment:
      - ROS_MASTER_URI=http://172.21.0.2:11311 # IP Address of ROS Master
      - ROS_HOSTNAME=172.21.0.3 # Own IP Address
    volumes:
      - ./data:/app/data
    command: ["tail", "-f", "/dev/null"]
    networks:
      - core_ros_network

networks:
  core_ros_network:
    external: true
